// src/components/vue/Avatar.vue
<template>
  <a
    class="s-avatar"
    v-bind:class="[
      size ? 's-avatar__' + size : 16,
      className
    ]"
    {...rest}
    v-bind:href="href"
  >
    <div class="s-avatar--letter" v-if="letter">{{letter}}</div>
    <img class="s-avatar--image" v-if="src" v-bind:alt="alt" v-bind:src="src" />
    <slot></slot>
  </a>
</template>

<script>
export default {
  name: "Avatar",
  props: {
    size: Number,
    src: String,
    alt: String,
    letter: String,
    className: String,
    href: String,
  },
};
</script>

// src/components/svelte/Avatar.svelte
<script>
  export let className = '', size = 16, letter = null, src = null, alt = null, href = null;
  let avatarSize = size ? `s-avatar__${size}` : 16;
</script>

<a class={`s-avatar ${avatarSize} ${className}`} href={href}>
  {#if letter}
    <div class="s-avatar--letter">{letter}</div>
  {/if}
  {#if src}
    <img class="s-avatar--image" src={src} alt={alt} />
  {/if}
  <slot></slot>
</a>
