// src/components/preact/Avatar.jsx
import { h, Fragment } from 'preact';
import View from './View';

export default function Avatar({
  alt,
  children,
  className = '',
  letter,
  size = 16,
  src,
  ...rest
}) {
  return (
    <View className={`s-avatar s-avatar__${size} ${className}`} {...rest}>
      {letter ? <div className="s-avatar--letter">{letter}</div> : ''}
      {src ? <img className="s-avatar--image" src={src} alt={alt} /> : ''}
      {children}
    </View>
  );
}

// src/components/svelte/Avatar.svelte
<script>
  export let className = '', size = 16, letter = null, src = null, alt = null;
  let avatarSize = size ? `s-avatar__${size}` : 16;
</script>

<span class={`s-avatar ${avatarSize} ${className}`}>
  {#if letter}
    <div class="s-avatar--letter">{letter}</div>
  {/if}
  {#if src}
    <img class="s-avatar--image" src={src} alt={alt} />
  {/if}
  <slot></slot>
</span>
