// src/components/react/Button.tsx
import React from 'react';
import View from './View';

const ButtonBadge = ({ children }) => (
  <View as="span" className="s-btn--badge ml4">
    <View as="span" className="s-btn--number">
      {children}
    </View>
  </View>
);

const Button = ({
  as = 'button',
  children,
  className = '',
  badge,
  modifier,
  dropdown,
  hasIcon,
  loading,
  size,
  variant = 'secondary',
  ...rest
}) => (
  <View
    as={as}
    className={`
      s-btn
      ${variant ? `s-btn__${variant}` : ''}
      ${modifier ? `s-btn__${modifier}` : ''}
      ${size ? `s-btn__${size}` : ''}
      ${dropdown ? 's-btn__dropdown' : ''}
      ${hasIcon ? 's-btn__icon' : ''}
      ${loading ? 'is-loading' : ''}
      ${className}
    `}
    {...rest}
  >
    {children}
    {badge ? <ButtonBadge>{badge}</ButtonBadge> : ''}
  </View>
);

export default Button;

// src/components/vue/Button.vue
<template>
  <button
    class="s-btn"
    v-bind:class="[
      variant ? 's-btn__' + variant : '',
      modifier ? 's-btn__' + modifier : '',
      size ? 's-btn__' + size : '',
      {
        's-btn__dropdown': dropdown,
        's-btn__item': hasIcon,
        'is-loading': loading,
      },
      className
    ]"
    {...rest}
  >
    <slot></slot>
  </button>
</template>

<script>
export default {
  name: "ButtonVue",
  props: {
    variant: String,
    modifier: String,
    size: String,
    dropdown: Boolean,
    hasIcon: Boolean,
    loading: Boolean,
    className: String,
  },
  // data() {
  //   return {
  //     count: 0,
  //   };
  // },
  // methods: {
  //   add() {
  //     this.count++;
  //   },
  //   subtract() {
  //     this.count--;
  //   },
  // },
};
</script>
