// src/components/vue/Avatar.vue
<template>
  <div
    class="s-avatar"
    v-bind:class="[
      size ? 's-avatar__' + size : 16,
      className
    ]"
    {...rest}
  >
    <div class="s-avatar--letter" v-if="letter">{{letter}}</div>
    <img class="s-avatar--image" v-if="src" v-bind:alt="alt" v-bind:src="src" />
    <slot></slot>
  </div>
</template>

<script>
export default {
  name: "Avatar",
  props: {
    size: Number,
    src: String,
    alt: String,
    letter: String,
    className: String,
  },
};
</script>

// src/components/react/Avatar.jsx
import React from 'react';
import View from './View';

// export type AvatarProps = ViewProps & {
//   /** Passed through to alt on img tag */
//   alt?: string;
//   /** A single character for displaying an abbreviated Team name */
//   letter?: string;
//   /** Width/height in pixels */
//   size?: 16 | 24 | 32 | 48 | 64 | 96 | 128;
//   /** Image url */
//   src?: string;
// };

/**
 * Avatars are used to quickly identify users or teams.
 */
const Avatar = ({
  alt,
  children,
  className = '',
  letter,
  size = 16,
  src,
  ...rest
}) => (
  <View className={`s-avatar s-avatar__${size} ${className}`} {...rest}>
    {letter ? <div className="s-avatar--letter">{letter}</div> : ''}
    {src ? <img className="s-avatar--image" src={src} alt={alt} /> : ''}
    {children}
  </View>
);

export default Avatar;
