// src/components/svelte/Badge.svelte
<script>
  export let className, bling, size, variant;
  let badgeVariant = variant ? `s-badge__${variant}` : '';
  let badgeSize = size ? `s-badge__${size}` : '';
  let badgeBling = bling ? `s-award-bling s-award-bling__${bling}` : '';
</script>

<span class={`s-badge ${badgeVariant} ${badgeSize} ${className || ''}`}>
  <span class={badgeBling}>
    <slot></slot>
  </span>
</span>

// src/components/react/Badge.jsx
import React from 'react';
import View from './View';

const Badge = ({
  as = 'span',
  children,
  className = '',
  bling,
  size,
  variant,
  ...rest
}) => (
  <View
    as={as}
    className={`
      s-badge
      ${variant ? `s-badge__${variant}` : ''}
      ${size ? `s-badge__${size}` : ''}
      ${className}
    `}
    {...rest}
  >
    <span className={bling ? `s-award-bling s-award-bling__${bling}` : ''}>
      {children}
    </span>
  </View>
);

export default Badge;
