// src/components/svelte/Button.svelte
<script>
  export let variant = 'secondary';
  export let className, modifier, size, dropdown, hasIcon, loading;
  let btnVariant = variant && `s-btn__${variant}`;
  let btnModifier = modifier && `s-btn__${modifier}`;
  let btnSize = size && `s-btn__${size}`;
  let btnDropdown = dropdown && 's-btn__dropdown';
  let btnIcon = hasIcon && 's-btn__icon';
  let btnLoading = loading && 'is-loading';
</script>

<button
  type="button"
  class={`s-btn ${btnVariant} ${btnModifier} ${btnSize} ${btnDropdown} ${btnIcon} ${btnLoading} ${className && className}`}>
  <slot></slot>
</button>

// src/components/preact/Button.jsx
import { h, Fragment } from 'preact';
import View from './View';

function ButtonBadge({ children }) {
  return (
    <View as="span" className="s-btn--badge ml4">
      <View as="span" className="s-btn--number">
        {children}
      </View>
    </View>
  );
}

export default function Button({
  as = 'button',
  children,
  className = '',
  badge,
  modifier,
  dropdown,
  hasIcon,
  loading,
  size,
  variant = 'secondary',
  ...rest
}) {
  return (
  <View
      as={as}
      className={`
        s-btn
        ${variant ? `s-btn__${variant}` : ''}
        ${modifier ? `s-btn__${modifier}` : ''}
        ${size ? `s-btn__${size}` : ''}
        ${dropdown ? 's-btn__dropdown' : ''}
        ${hasIcon ? 's-btn__icon' : ''}
        ${loading ? 'is-loading' : ''}
        ${className}
      `}
      {...rest}
    >
      {children}
      {badge ? <ButtonBadge>{badge}</ButtonBadge> : ''}
    </View>
  );
}
